# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76f4401cbe0e33ebd9b361e0aae1345f71dc2cb15d4524eedf33e2bded07feb840f39ec1f5aad35390aa13ff0e5d4dd0ec41c09d6930616818187047812886af

test:
  secret_key_base: b86c2d200c833d8176dd84e468206c2bbed8504de5cb01cf680fa84ce6f14585f659b4de9897491bce02aeee5ba862b1dd5e8b47be92b8b23ba07d5f29190462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
